### ISSUE TITLE
Make nexus loader open files in read only mode by default?

### ISSUE THREAD

**Issue by jokasimr** [scipp/essreduce#79] opened 2024-08-23 14:10 UTC
When opening files on the raw data filesystem (like we do in `dmsc-nightly`) we need to open them in read only mode, because the file system is read only and h5py raises an error if we don't.

Encountered that issue here: https://git.esss.dk/dmsc-nightly/dmsc-nightly/-/jobs/40056

Do the nexus loaders in the essreduce repo need some mechanism for passing arguments (like read mode flag) to the file opener?

We rarely write to the nexus files we load using the nexus loading tools in essreduce.
Would it make sense to make the file-loader tools in this repo open files in read-only mode by default?

**Comment by SimonHeybrock** [comment] 2024-08-26 05:41
ScippNexus forwards to `h5py.File` (not setting any custom mode): https://github.com/scipp/scippnexus/blob/1ce744454627282885818724d96d2a79993d9d67/src/scippnexus/file.py#L17-L23

And `h5py`[says](https://docs.h5py.org/en/stable/high/file.html#opening-creating-files):

> Changed in version 3.0: Files are now opened read-only by default. Earlier versions of h5py would pick different modes depending on the presence and permissions of the file.

Are you saying this is not the case? Can you clarify how to reproduce, or tell that it is not read-only?

**Comment by SimonHeybrock** [comment] 2024-09-25 09:51
Duplicate of #99.

**Closed by SimonHeybrock** 2024-09-25 09:51 UTC
Labels: bug, enhancement
